In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import Binarizer, Imputer, \
    OneHotEncoder, PolynomialFeatures, StandardScaler, \
    MinMaxScaler, RobustScaler

In [2]:
df = pd.read_csv('datasets/train.csv')
df.head()

school sex   age address famsize Pstatus  Medu  Fedu     Mjob      Fjob ...  \
0     GP   F  18.0       U     GT3       A     4     4  at_home   teacher ...   
1     GP   F  15.0       U     LE3       T     1     1  at_home     other ...   
2     GP   F   NaN       U     GT3       T     4     2   health  services ...   
3     GP   F  16.0       U     GT3       T     3     3    other     other ...   
4     GP   F   NaN       U     GT3       A     4     4    other   teacher ...   

  famrel freetime  goout  Dalc  Walc health absences  G1    G2  G3  
0      4        3      4     1     1      3        6   5   6.0   6  
1      4        3      2     2     3      3       10   7   8.0  10  
2      3        2      2     1     1      5        2  15   NaN  15  
3      4        3      2     1     2      5        4   6  10.0  10  
4      4        1      4     1     1      1        6   6   5.0   6  

[5 rows x 33 columns]

In [3]:
test_df = pd.read_csv('datasets/test.csv')
test_df.head()

school sex   age address famsize Pstatus  Medu  Fedu      Mjob   Fjob ...  \
0     GP   F  17.0       U     GT3       T     1     1   at_home  other ...   
1     GP   M   NaN       U     LE3       T     4     3  services  other ...   
2     GP   M  16.0       U     LE3       T     2     2     other  other ...   
3     GP   M  15.0       U     GT3       T     3     4     other  other ...   
4     GP   F   NaN       U     GT3       T     2     1  services  other ...   

  famrel freetime  goout  Dalc  Walc health absences  G1    G2  G3  
0      5        3      3     1     1      3        4   5   5.0   6  
1      5        4      2     1     2      5       10  15  15.0  15  
2      4        4      4     1     1      3        0  12  12.0  11  
3      5        5      1     1     1      5        0  14  15.0  15  
4      5        2      2     1     1      4        4  10  12.0  12  

[5 rows x 33 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 190 entries, 0 to 189
Data columns (total 33 columns):
school        190 non-null object
sex           190 non-null object
age           147 non-null float64
address       190 non-null object
famsize       190 non-null object
Pstatus       190 non-null object
Medu          190 non-null int64
Fedu          190 non-null int64
Mjob          190 non-null object
Fjob          190 non-null object
reason        190 non-null object
guardian      190 non-null object
traveltime    190 non-null int64
studytime     190 non-null int64
failures      190 non-null int64
schoolsup     190 non-null object
famsup        190 non-null object
paid          190 non-null object
activities    190 non-null object
nursery       190 non-null object
higher        190 non-null object
internet      190 non-null object
romantic      190 non-null object
famrel        190 non-null int64
freetime      190 non-null int64
goout         190 non-null int64
Dalc          190 

In [5]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 33 columns):
school        205 non-null object
sex           205 non-null object
age           155 non-null float64
address       205 non-null object
famsize       205 non-null object
Pstatus       205 non-null object
Medu          205 non-null int64
Fedu          205 non-null int64
Mjob          205 non-null object
Fjob          205 non-null object
reason        205 non-null object
guardian      205 non-null object
traveltime    205 non-null int64
studytime     205 non-null int64
failures      205 non-null int64
schoolsup     205 non-null object
famsup        205 non-null object
paid          205 non-null object
activities    205 non-null object
nursery       205 non-null object
higher        205 non-null object
internet      205 non-null object
romantic      205 non-null object
famrel        205 non-null int64
freetime      205 non-null int64
goout         205 non-null int64
Dalc          205 

In [9]:
# Testing Reshape 
numpy_array = df['G1'].values.reshape(-1,1)

In [13]:
numpy_array.shape

(190, 1)

In [14]:
numpy_array[0:5, :]

array([[ 5],
       [ 7],
       [15],
       [ 6],
       [ 6]])

In [17]:
g1_b = Binarizer(10) 
g1_b.fit(df['G1'].values.reshape(-1,1))
g1_grades = g1_b.transform(df['G1'].values.reshape(-1,1))
print (g1_grades[0:5,:], g1_grades.mean())

[[0]
 [0]
 [1]
 [0]
 [0]] 0.473684210526


In [18]:
g1_grades_test = g1_b.transform(test_df['G1'].values.reshape(-1,1))

In [19]:
print (g1_grades_test[0:5:, ], g1_grades_test.mean())

[[0]
 [1]
 [1]
 [1]
 [0]] 0.546341463415
